# -*- coding: utf-8 -*-
"""CSV/XLSX column extraction and merge logic used by the GUI."""

from __future__ import annotations

import csv
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, List, Optional, Sequence, Tuple

import pandas as pd


SUPPORTED_SOURCE_EXTENSIONS = {".csv", ".xlsx"}
SUPPORTED_TEMPLATE_EXTENSIONS = {".csv", ".xlsx"}
ENCODING_CANDIDATES = (
    "utf-8-sig",
    "utf-8",
    "gb18030",
    "gbk",
    "big5",
    "latin1",
)
TEMPLATE_HEADER_NAMES = {
    "列名",
    "待提取列名",
    "提取列名",
    "字段名",
    "表头",
    "column",
    "columns",
    "field",
    "fields",
    "header",
    "headers",
}
RESERVED_COLUMNS = {"Source_File", "Source_Sheet"}

ProgressCallback = Callable[[int, int, str], None]


@dataclass(frozen=True)
class MergeResult:
    """Summary returned after a merge operation."""

    output_path: Path
    source_file_count: int
    successful_file_count: int
    total_rows: int
    failed_files: Tuple[Tuple[str, str], ...]
    extracted_columns: Tuple[str, ...]


def _clean_cell(value: object) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    return "" if text.lower() == "nan" else text


def _detect_separator(file_path: Path, encoding: str) -> str:
    """Detect common CSV delimiters, falling back to a comma."""

    with file_path.open("r", encoding=encoding, newline="") as handle:
        sample = handle.read(65536)

    if not sample:
        return ","

    try:
        return csv.Sniffer().sniff(sample, delimiters=",;\t|").delimiter
    except csv.Error:
        return ","


def read_csv_with_auto_encoding(
    file_path: Path,
    *,
    header: Optional[int] = 0,
) -> pd.DataFrame:
    """Read a CSV as text using common encodings and delimiter detection."""

    last_error: Optional[Exception] = None
    for encoding in ENCODING_CANDIDATES:
        try:
            separator = _detect_separator(file_path, encoding)
            return pd.read_csv(
                file_path,
                encoding=encoding,
                sep=separator,
                header=header,
                dtype=str,
                keep_default_na=False,
                low_memory=False,
                on_bad_lines="warn",
            )
        except Exception as exc:  # Try the next likely encoding.
            last_error = exc

    raise RuntimeError(f"无法读取 CSV：{file_path.name}；{last_error}")


def read_template_columns(template_path: Path) -> List[str]:
    """Read column names from the first non-empty column of a CSV/XLSX template."""

    template_path = Path(template_path)
    if not template_path.is_file():
        raise FileNotFoundError(f"模板文件不存在：{template_path}")

    suffix = template_path.suffix.lower()
    if suffix not in SUPPORTED_TEMPLATE_EXTENSIONS:
        raise ValueError("模板文件仅支持 CSV 或 XLSX 格式")

    if suffix == ".xlsx":
        frame = pd.read_excel(
            template_path,
            sheet_name=0,
            header=None,
            dtype=str,
            keep_default_na=False,
            engine="openpyxl",
        )
    else:
        frame = read_csv_with_auto_encoding(template_path, header=None)

    values: List[str] = []
    for column in frame.columns:
        candidate = [_clean_cell(value) for value in frame[column].tolist()]
        candidate = [value for value in candidate if value]
        if candidate:
            values = candidate
            break

    if not values:
        raise ValueError("模板的第一个工作表中没有找到有效列名")

    if values[0].casefold() in TEMPLATE_HEADER_NAMES:
        values = values[1:]

    # Source columns are always generated by the application itself.
    values = [value for value in values if value not in RESERVED_COLUMNS]
    if not values:
        raise ValueError("模板中没有可提取的业务列名")

    seen = set()
    duplicates = []
    for value in values:
        if value in seen and value not in duplicates:
            duplicates.append(value)
        seen.add(value)
    if duplicates:
        preview = "、".join(duplicates[:5])
        raise ValueError(f"模板包含重复列名，请先删除重复项：{preview}")

    return values


def collect_source_files(
    input_dir: Path,
    *,
    recursive: bool = False,
    excluded_paths: Sequence[Path] = (),
) -> List[Path]:
    """Collect CSV/XLSX source files, including upper-case extensions."""

    input_dir = Path(input_dir)
    if not input_dir.exists():
        raise FileNotFoundError(f"输入文件夹不存在：{input_dir}")
    if not input_dir.is_dir():
        raise NotADirectoryError(f"输入路径不是文件夹：{input_dir}")

    excluded = {Path(path).resolve() for path in excluded_paths}
    candidates = input_dir.rglob("*") if recursive else input_dir.iterdir()
    source_files = [
        path
        for path in candidates
        if path.is_file()
        and path.suffix.lower() in SUPPORTED_SOURCE_EXTENSIONS
        and not path.name.startswith("~$")
        and path.resolve() not in excluded
    ]
    return sorted(source_files, key=lambda path: str(path).casefold())


def _read_xlsx_sheets(file_path: Path, all_sheets: bool) -> List[Tuple[str, pd.DataFrame]]:
    with pd.ExcelFile(file_path, engine="openpyxl") as workbook:
        sheet_names = workbook.sheet_names if all_sheets else workbook.sheet_names[:1]
        return [
            (
                sheet_name,
                pd.read_excel(
                    workbook,
                    sheet_name=sheet_name,
                    dtype=str,
                    keep_default_na=False,
                ),
            )
            for sheet_name in sheet_names
        ]


def _read_source(file_path: Path, excel_all_sheets: bool) -> List[Tuple[str, pd.DataFrame]]:
    if file_path.suffix.lower() == ".csv":
        return [("", read_csv_with_auto_encoding(file_path))]
    return _read_xlsx_sheets(file_path, excel_all_sheets)


def _extract_columns(
    frame: pd.DataFrame,
    required_columns: Sequence[str],
    source_file: str,
    source_sheet: str,
) -> pd.DataFrame:
    mapping = {}
    for original_column in frame.columns:
        clean_column = str(original_column).strip()
        if clean_column not in mapping:
            mapping[clean_column] = original_column

    row_count = len(frame)
    data = {
        "Source_File": [source_file] * row_count,
        "Source_Sheet": [source_sheet] * row_count,
    }
    for column in required_columns:
        original_column = mapping.get(column)
        if original_column is None:
            data[column] = [""] * row_count
        else:
            data[column] = frame[original_column].to_numpy(copy=False)

    return pd.DataFrame(data, columns=["Source_File", "Source_Sheet", *required_columns])


def merge_folder(
    input_dir: Path,
    output_path: Path,
    template_path: Path,
    *,
    recursive: bool = False,
    excel_all_sheets: bool = False,
    progress_callback: Optional[ProgressCallback] = None,
) -> MergeResult:
    """Extract template columns from every source file and atomically write one CSV."""

    input_dir = Path(input_dir)
    output_path = Path(output_path)
    template_path = Path(template_path)

    required_columns = read_template_columns(template_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    source_files = collect_source_files(
        input_dir,
        recursive=recursive,
        excluded_paths=(template_path, output_path),
    )
    if not source_files:
        raise FileNotFoundError("输入文件夹中没有找到 CSV 或 XLSX 文件")

    temp_handle = tempfile.NamedTemporaryFile(
        prefix=f".{output_path.stem}_",
        suffix=".tmp",
        dir=output_path.parent,
        delete=False,
    )
    temp_path = Path(temp_handle.name)
    temp_handle.close()

    first_write = True
    total_rows = 0
    successful_files = 0
    failed_files: List[Tuple[str, str]] = []

    try:
        total_files = len(source_files)
        for index, file_path in enumerate(source_files, start=1):
            try:
                frames = [
                    _extract_columns(
                        frame,
                        required_columns,
                        source_file=file_path.name,
                        source_sheet=sheet_name,
                    )
                    for sheet_name, frame in _read_source(file_path, excel_all_sheets)
                ]
                file_frame = pd.concat(frames, ignore_index=True) if frames else pd.DataFrame(
                    columns=["Source_File", "Source_Sheet", *required_columns]
                )
                file_frame.to_csv(
                    temp_path,
                    mode="w" if first_write else "a",
                    index=False,
                    header=first_write,
                    encoding="utf-8-sig" if first_write else "utf-8",
                )
                first_write = False
                successful_files += 1
                total_rows += len(file_frame)
                message = f"[{index}/{total_files}] 已完成：{file_path.name}（{len(file_frame)} 行）"
            except Exception as exc:
                error_text = str(exc) or exc.__class__.__name__
                failed_files.append((file_path.name, error_text))
                message = f"[{index}/{total_files}] 处理失败：{file_path.name}；{error_text}"

            if progress_callback:
                progress_callback(index, total_files, message)

        if successful_files == 0:
            first_error = failed_files[0][1] if failed_files else "未知错误"
            raise RuntimeError(f"所有源文件均处理失败。第一个错误：{first_error}")

        os.replace(temp_path, output_path)
    finally:
        if temp_path.exists():
            try:
                temp_path.unlink()
            except OSError:
                pass

    return MergeResult(
        output_path=output_path,
        source_file_count=len(source_files),
        successful_file_count=successful_files,
        total_rows=total_rows,
        failed_files=tuple(failed_files),
        extracted_columns=tuple(required_columns),
    )

